### ISSUE TITLE
Analysis with only selected columns 

### ISSUE THREAD

**Issue by anananwal** [broadinstitute/protigy#11]
Since the recent update, which includes the option to chose Experiment or group column for testing, I can't seem to do statistical tests on only a few selected replicates (to leave out dropouts for example). 
If I do not fill in the experiment column in the experimental design file it still includes this sample in the analysis. 
Previously leaving the experimental column cell blank for a sample excluded it from analysis. 
Is there a new way of doing this? 

Example: 
When trying to exclude one replicate from one experiment it puts that sample as an unnamed experiment with one sample in (see first attached screenshot). <img width="296" alt="Screenshot 2022-07-29 at 12 27 40" src="https://user-images.githubusercontent.com/109970663/181740486-b0f6f0f9-8564-4f7b-9d6a-69f41361293a.png">
Then I get this error when I try to run a moderated t test:
Warning: Error in apply: dim(X) must have a positive length

Example 2:
See 2nd attached screenshot of 8 unwanted samples being included together as unnamed experiment.
<img width="280" alt="Screenshot 2022-07-29 at 12 17 43" src="https://user-images.githubusercontent.com/109970663/181739427-e95c9c95-6eea-4429-bd92-d40751dac858.png">
<img width="296" alt="Screenshot 2022-07-29 at 12 27 40" src="https://user-images.githubusercontent.com/109970663/181740486-b0f6f0f9-8564-4f7b-9d6a-69f41361293a.png">

**Comment by nmclark2** [comment]
Hi,

Samples that you wish to exclude in the experimental design file must use `NA` instead of `""` now. This was changed due to an issue in how Protigy interprets blank values. If you re-download the experimental design template from Protigy, you will notice that the default value is now `NA` instead of `""` Changing blank values to `NA` in your experimental design file should fix this issue. Please let me know if it does not. 

Thanks,
Natalie

**Comment by nmclark2** [comment]
@anananwal were you able to resolve this issue? Please let me know if not. Otherwise I will close it. Thank you.

**Comment by anananwal** [comment]
Yes, I did. Thank you so much for the quick solution. Sorry I didn’t reply!

On 19. Sep 2022, at 22:08, Natalie Clark ***@***.***> wrote:

﻿

@anananwal<https://github.com/anananwal> were you able to resolve this issue? Please let me know if not. Otherwise I will close it. Thank you.
