### ISSUE TITLE
error in downloading protigy through shiny in R

### ISSUE THREAD

**Issue by auromahima** [broadinstitute/protigy#9]
> shiny::runGitHub("protigy", "broadinstitute")
Downloading https://github.com/broadinstitute/protigy/archive/master.tar.gz
Error in utils::download.file(url, method = method, ...) : 
  download from 'https://github.com/broadinstitute/protigy/archive/master.tar.gz' failed
In addition: Warning message:
In utils::download.file(url, method = method, ...) :
  URL 'https://codeload.github.com/broadinstitute/protigy/tar.gz/master': Timeout of 60 seconds was reached

Can anyone help me with this, please !

**Comment by karstenkrug** [comment]
I am not able to reproduce the error. Could you please make sure you are connected to the internet and try again? Please also disconnect from any VPNs you might be running.

**Comment by auromahima** [comment]
I am connected to internet and disconnected from VPN. I also tried uninstalling and reinstalling shiny. Still doesn't work. 
System - MacOS mojave (10.14.6)
R version - 4.1.0
Is there any other way by which I can load Protigy !

**Comment by auromahima** [comment]
Problem solved. It was timeout issue.
Thank you for your reply though @karstenkrug .

**Comment by karstenkrug** [comment]
Glad it worked!
